[GITHUB-14] Add missing configuration options
sansible/users_and_groups pull request #15
Opened 2016-12-23 16:19 UTC by chroche

- Add users_and_groups.users.home key to define user's home directory.
 - Add users_and_groups.authorized_keys_dir to define global SSH keys directory.

2017-01-04 11:49 UTC, lobsterdore commented on tasks/build.yml
> +- name: Copy ssh auth keys to authorized_keys directory
Do we need auth keys to exist in the default and overridden directory?

2017-01-05 14:45 UTC, chroche commented on tasks/build.yml
> +- name: Copy ssh auth keys to authorized_keys directory
This happens only when the overridden dir is defined:
```
 when: (users_and_groups.authorized_keys_dir is defined)
```
Yes this is a bit clumsy :-/

2017-01-05 20:55 UTC, wojtek-oledzki requested changes

2017-01-05 20:55 UTC, wojtek-oledzki commented on tests/test.yml
> +      shell: id -u whitelistedgroup.user
can you change that to `command` as well pls?

2017-01-05 20:55 UTC, wojtek-oledzki commented on tests/test.yml
> +      command: "grep -E 'ipsum\\s+ALL=\\(ALL\\)\\s+NOPASSWD: ALL' /etc/sudoers.d/ipsum"
:+1:

2017-01-05 20:55 UTC, wojtek-oledzki commented on tasks/build.yml
> +    owner: "root"
why is it hardcoded to "root"?

2017-01-05 20:55 UTC, wojtek-oledzki commented on tasks/build.yml
> +- name: Copy ssh auth keys to authorized_keys directory
Can we check for "null" instead of "defined", and have defaults set to null?

```YAML
users_and_groups:
  authorized_keys_dir: ~
```

2017-01-17 17:22 UTC, chroche commented on tasks/build.yml
> +    owner: "root"
This directory is accessed by SSHd and typically set to /etc/ssh/authorized_keys/, so this makes sense?

2017-01-17 17:24 UTC, chroche commented on tests/test.yml
> +      shell: id -u whitelistedgroup.user
Ok

2017-01-17 17:40 UTC, chroche commented on tasks/build.yml
> +- name: Copy ssh auth keys to authorized_keys directory
Ok

2017-01-23 15:02 UTC, wojtek-oledzki commented on tasks/build.yml
> +    owner: "root"
true, if we ever need to run sshd as other user, then we can change that to a variable. For now hardcoded `root` is fine

2017-01-23 15:07 UTC, wojtek-oledzki approved these changes

2017-01-23 15:09 UTC, wojtek-oledzki commented
Looks good to me :tm:

![LGTM](https://m.popkey.co/45f7ae/X1kgw_f-maxage-0.gif)

2017-01-23 15:28 UTC, lobsterdore commented
LGTM 👍

2017-01-23 15:58 UTC, quater commented on README.md
>  In most cases you would keep the list of users in external vars file or
I had a chat with @chroche and it all sounds feasible. However I would prefer a more detailed documentation.

2017-01-23 16:00 UTC, quater commented
This is the corresponding GitHub issues https://github.com/sansible/users_and_groups/issues/14

2017-02-01 12:13 UTC, merged